"use client";

import { useState } from "react";
import { ArrowUpRight, Gauge, MapPin, Search, Factory, TriangleAlert } from "lucide-react";
import type { Section } from "@/app/page";

const machines = [
  { id: "BL-5702", name: "Product Blower", area: "Process bay", status: "Running", health: "98.6%", oee: "96.4%", temp: "58°C", x: "24%", y: "32%" },
  { id: "HE-3301", name: "Feed / Effluent Heat Exchanger", area: "Heat bay", status: "Running", health: "94.2%", oee: "92.1%", temp: "71°C", x: "54%", y: "27%" },
  { id: "PM-4405B", name: "Cooling Water Pump", area: "Utilities bay", status: "Attention", health: "87.3%", oee: "84.8%", temp: "82°C", x: "76%", y: "38%" },
  { id: "KO-3201", name: "Cracked Gas Compressor", area: "Compression bay", status: "Running", health: "96.8%", oee: "94.7%", temp: "63°C", x: "39%", y: "71%" },
  { id: "PU-2101B", name: "Feed Charge Pump", area: "Pump bay", status: "Idle", health: "91.3%", oee: "89.4%", temp: "49°C", x: "72%", y: "72%" },
];
const bottomMetrics = [["Production", "92.4%", "+2.1%"], ["OEE", "87.0%", "+3.4%"], ["Downtime", "4.2 h", "-12.5%"], ["Active issues", "12", "3 new"]];
interface OverviewContentProps { onNavigate: (section: Section) => void; }

export function OverviewContent({ onNavigate }: OverviewContentProps) {
  const [selectedId, setSelectedId] = useState("BL-5702");
  const selected = machines.find((machine) => machine.id === selectedId) ?? machines[0];
  return <div className="min-h-full space-y-5 bg-[#f4f6fa] p-2 text-[#172337] sm:p-4">
    <section className="flex flex-wrap items-end justify-between gap-4 px-1 pt-1 sm:px-2"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-[#5f7896]"><MapPin className="h-3.5 w-3.5 text-[#1f9abf]" />Plant A — West Jakarta</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-[#15243a]">Live factory view</h2><p className="mt-1 text-sm text-[#718198]">Production floor status · Oct 1, 2026 · 14:32</p></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-xl border border-[#d7dee9] bg-white px-3 py-2 text-sm text-[#8290a3] lg:flex"><Search className="h-4 w-4" />Search equipment, problem, or insight...</div><button type="button" className="rounded-xl border border-[#d7dee9] bg-white px-4 py-2 text-sm font-medium text-[#45576f]">Today⌄</button><button type="button" className="rounded-xl border border-[#d7dee9] bg-white px-4 py-2 text-sm font-medium text-[#45576f]">All shifts⌄</button></div></section>
    <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_290px]">
      <div className="relative min-h-[570px] overflow-hidden rounded-[22px] border border-[#ccd7e2] bg-[#dbe3ea] p-3 shadow-[0_14px_36px_rgba(36,58,84,0.10)] sm:p-6">
        <div className="absolute inset-0 opacity-35" style={{ backgroundImage: "linear-gradient(#b7c5d1 1px, transparent 1px), linear-gradient(90deg, #b7c5d1 1px, transparent 1px)", backgroundSize: "32px 32px" }} />
        <div className="relative h-[518px] overflow-hidden rounded-xl border-[10px] border-[#b6c3ce] bg-[#eff3f5] shadow-[inset_0_0_0_2px_#ffffff]">
          <div className="absolute left-[5%] top-[8%] h-[37%] w-[39%] rounded-lg border-4 border-[#aab9c5] bg-[#d9e2e8] shadow-[inset_0_0_0_3px_#edf3f6]"><span className="absolute left-4 top-3 text-[10px] font-bold uppercase tracking-[0.14em] text-[#718397]">Process bay</span><div className="absolute bottom-8 left-8 h-16 w-24 rounded border-2 border-[#aebdc8] bg-[#c4d1d9]" /><div className="absolute bottom-10 right-8 h-20 w-14 rounded border-2 border-[#aebdc8] bg-[#c4d1d9]" /></div>
          <div className="absolute right-[5%] top-[8%] h-[37%] w-[42%] rounded-lg border-4 border-[#aab9c5] bg-[#e2e9ed] shadow-[inset_0_0_0_3px_#f4f7f8]"><span className="absolute left-4 top-3 text-[10px] font-bold uppercase tracking-[0.14em] text-[#718397]">Heat & utilities</span><div className="absolute bottom-8 left-8 h-12 w-20 rounded border-2 border-[#aebdc8] bg-[#cbd7de]" /><div className="absolute bottom-8 right-10 h-16 w-16 rounded-full border-4 border-[#aebdc8] bg-[#d0dbe1]" /></div>
          <div className="absolute bottom-[8%] left-[5%] h-[38%] w-[43%] rounded-lg border-4 border-[#aab9c5] bg-[#e4eaed] shadow-[inset_0_0_0_3px_#f6f8f9]"><span className="absolute left-4 top-3 text-[10px] font-bold uppercase tracking-[0.14em] text-[#718397]">Compression bay</span><div className="absolute bottom-8 left-8 h-14 w-28 rounded-full border-2 border-[#aebdc8] bg-[#cbd7de]" /><div className="absolute bottom-8 right-10 h-14 w-20 rounded border-2 border-[#aebdc8] bg-[#cbd7de]" /></div>
          <div className="absolute bottom-[8%] right-[5%] h-[38%] w-[35%] rounded-lg border-4 border-[#aab9c5] bg-[#d9e3e8] shadow-[inset_0_0_0_3px_#edf3f6]"><span className="absolute left-4 top-3 text-[10px] font-bold uppercase tracking-[0.14em] text-[#718397]">Pump bay</span><div className="absolute bottom-8 left-8 h-16 w-12 rounded-full border-4 border-[#aebdc8] bg-[#c6d3da]" /><div className="absolute bottom-8 right-8 h-12 w-16 rounded border-2 border-[#aebdc8] bg-[#c6d3da]" /></div>
          <div className="absolute left-1/2 top-1/2 h-3/4 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#b7c7d2]" />
          {machines.map((machine) => <button key={machine.id} type="button" onClick={() => setSelectedId(machine.id)} className={`group absolute -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-white p-1.5 shadow-[0_4px_14px_rgba(18,87,199,0.35)] transition-all duration-300 hover:scale-125 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#178ee5]/30 ${selected.id === machine.id ? "scale-125 bg-[#178ee5]" : machine.status === "Attention" ? "bg-[#edac28]" : "bg-[#326b9f]"}`} style={{ left: machine.x, top: machine.y }} aria-label={`Open ${machine.name}`}><span className="block h-3 w-3 rounded-full bg-white" /><span className="pointer-events-none absolute left-full top-1/2 ml-2 -translate-y-1/2 whitespace-nowrap rounded-md bg-[#1c2c3f] px-2.5 py-1.5 text-[10px] font-semibold text-white shadow-lg">{machine.id}</span></button>)}
          <div className="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-lg bg-white/90 px-3 py-2 text-xs font-medium text-[#62748a] shadow-sm">Click a machine marker to inspect equipment</div>
        </div>
      </div>
      <aside className="rounded-2xl border border-[#d7dee9] bg-white p-5 shadow-[0_10px_28px_rgba(36,58,84,0.08)]"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#7c8ca2]">Selected equipment</p><h3 className="mt-2 text-xl font-bold text-[#15243a]">{selected.id}</h3><p className="mt-1 text-sm text-[#718198]">{selected.name}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${selected.status === "Attention" ? "bg-[#fff4d9] text-[#ad7412]" : "bg-[#e4f7ef] text-[#16865d]"}`}>{selected.status}</span></div><div className="my-5 flex h-36 items-center justify-center rounded-xl bg-[#eff3f7]"><Factory className="h-20 w-20 text-[#8fa3b7]" /></div><div className="space-y-3 text-sm"><div className="flex justify-between border-b border-[#edf0f4] pb-3"><span className="text-[#7c8ca2]">Area</span><strong>{selected.area}</strong></div><div className="flex justify-between border-b border-[#edf0f4] pb-3"><span className="text-[#7c8ca2]">OEE</span><strong className="text-[#e45c63]">{selected.oee}</strong></div><div className="flex justify-between border-b border-[#edf0f4] pb-3"><span className="text-[#7c8ca2]">Temperature</span><strong>{selected.temp}</strong></div><div className="flex justify-between"><span className="text-[#7c8ca2]">Health</span><strong className="text-[#16865d]">{selected.health}</strong></div></div><button type="button" onClick={() => onNavigate("equipment")} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#233c58] px-4 py-3 text-sm font-semibold text-white transition-colors hover:bg-[#172d45]">View equipment details <ArrowUpRight className="h-4 w-4" /></button></aside>
    </section>
    <section className="grid gap-4 xl:grid-cols-[1.2fr_1fr_1fr]"><div className="rounded-2xl border border-[#d7dee9] bg-white p-5"><div className="mb-4 flex items-center gap-2"><Gauge className="h-4 w-4 text-[#1f9abf]" /><h3 className="font-bold text-[#24364c]">Plant performance</h3></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-4">{bottomMetrics.map(([label, value, change]) => <div key={label}><p className="text-xs text-[#8492a5]">{label}</p><p className="mt-1 text-xl font-bold text-[#253a54]">{value}</p><p className={`mt-1 text-xs font-semibold ${label === "Downtime" || label === "Active issues" ? "text-[#ef626c]" : "text-[#26a26f]"}`}>{change}</p></div>)}</div></div><div className="rounded-2xl border border-[#d7dee9] bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-bold text-[#24364c]">Production output</h3><span className="text-xs text-[#8492a5]">Today</span></div><div className="mt-5 flex h-20 items-end gap-1">{[34,40,42,55,48,61,58,73,66,78,69,82,76,88,79,91,84,93,77,86].map((height, index) => <div key={index} className="flex-1 rounded-t bg-[#76b8df]" style={{ height: `${height}%` }} />)}</div></div><div className="rounded-2xl border border-[#d7dee9] bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-bold text-[#24364c]">Active alerts</h3><span className="text-xs font-semibold text-[#238dc0]">View all →</span></div><div className="mt-4 space-y-3 text-xs text-[#586b82]"><p><TriangleAlert className="mr-2 inline h-3.5 w-3.5 text-[#ef626c]" />{selected.id} — Temperature high</p><p><TriangleAlert className="mr-2 inline h-3.5 w-3.5 text-[#ef626c]" />Line 03 — Unexpected stop</p><p><TriangleAlert className="mr-2 inline h-3.5 w-3.5 text-[#f2ba29]" />Press-02 — Vibration anomaly</p></div></div></section>
  </div>;
}

export default OverviewContent;
