"use client";

import { useState } from "react";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, CheckCircle2, ChevronDown, CircleGauge, Database, Factory, ShieldAlert, TrendingUp } from "lucide-react";

const machines = [
  { id: "BL-5702", name: "Product Blower", status: "NORMAL", health: "98.4%", risk: "Low", color: "bg-[#1d68d4]" },
  { id: "HE-3301", name: "Feed/Effluent Heat Exchanger", status: "NORMAL", health: "96.8%", risk: "Low", color: "bg-[#1d68d4]" },
  { id: "PM-4405B", name: "Cooling Water Pump", status: "WATCH", health: "89.6%", risk: "Medium", color: "bg-[#f0a23a]" },
  { id: "KO-3201", name: "Cracked Gas Compressor", status: "NORMAL", health: "97.2%", risk: "Low", color: "bg-[#1d68d4]" },
  { id: "PU-2101B", name: "Feed Charge Pump", status: "WATCH", health: "91.3%", risk: "Medium", color: "bg-[#f0a23a]" },
];

const conditionHistory = [
  ["2026-01-28", "4.004", "1.143", "0.025", "60.7", "NORMAL"],
  ["2026-02-04", "4.188", "1.287", "0.034", "59.2", "NORMAL"],
  ["2026-02-11", "4.091", "1.293", "0.037", "60.7", "NORMAL"],
];

const performanceSummary = [
  ["Monitoring Period (weeks)", "26"], ["Total Downtime (hours)", "14"], ["Period Hours", "4368"], ["Availability (%)", "99.7"], ["No. of Failures (period)", "1"], ["MTBF (hours)", "4368"], ["MTTR (hours)", "14"], ["ALARM readings", "15"], ["TRIP readings", "1"], ["NORMAL readings", "10"], ["PM Compliance (%)", "92.0"], ["Production Loss (ton)", "532"], ["Estimated Loss (k USD)", "478.8"],
];

const insights = [
  { title: "Bearing vibration trend is rising", text: "BL-5702 2X harmonic increased 13.1% across the last three readings. This is below trip level but can indicate coupling misalignment.", tag: "Early warning", tone: "amber", evidence: "2X harmonic moved from 1.143 to 1.293 mm/s while coupling offset reached 0.037 mm.", action: "Inspect coupling alignment and confirm bearing lubrication during the next planned maintenance window." },
  { title: "Cooling pump has the highest exposure", text: "PM-4405B has 11 alarm readings in the current window. Check seal condition and suction pressure before the next planned run.", tag: "Medium risk", tone: "red", evidence: "Repeated alarm weeks correlate with reduced availability and unstable suction pressure readings.", action: "Check suction strainer, seal condition, and pump inlet pressure before returning the asset to full load." },
  { title: "Maintenance window opportunity", text: "PU-2101B is operating at 91.3% health with no active trip. Align inspection with the next scheduled production changeover.", tag: "Recommended", tone: "blue", evidence: "Health is below the plant baseline but remains stable with no current trip event.", action: "Schedule a targeted inspection at changeover and trend vibration after the first post-maintenance run." },
];

export function PerformanceContent() {
  const [selectedMachine, setSelectedMachine] = useState("BL-5702");
  const [selectedInsight, setSelectedInsight] = useState(0);
  const machine = machines.find((item) => item.id === selectedMachine) ?? machines[0];
  const activeInsight = insights[selectedInsight] ?? insights[0];

  return (
    <div className="space-y-6">
      <section className="grid gap-4 xl:grid-cols-[1.35fr_1fr]">
        <div className="rounded-2xl border border-[#dce7f7] bg-white p-6 shadow-[0_8px_24px_rgba(8,47,128,0.06)]">
          <div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-[#7890b2]"><Database className="h-4 w-4 text-[#1257c7]" />Condition intelligence</div><h2 className="mt-3 text-xl font-semibold text-[#082f80]">Unseen trouble detection</h2><p className="mt-1 max-w-2xl text-sm text-[#6c83a4]">Root-cause signals from vibration, temperature, pressure, and maintenance history.</p></div><span className="rounded-full bg-[#eaf8ef] px-3 py-1.5 text-xs font-bold text-[#25824b]">Database synced</span></div>
          <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#f6f9fe] p-4"><p className="text-xs text-[#7890b2]">Assets monitored</p><p className="mt-2 text-2xl font-semibold text-[#082f80]">05</p></div><div className="rounded-xl bg-[#f6f9fe] p-4"><p className="text-xs text-[#7890b2]">Early warnings</p><p className="mt-2 text-2xl font-semibold text-[#c27d18]">02</p></div><div className="rounded-xl bg-[#f6f9fe] p-4"><p className="text-xs text-[#7890b2]">Root causes found</p><p className="mt-2 text-2xl font-semibold text-[#082f80]">03</p></div></div>
        </div>
        <div className="rounded-2xl border border-[#dce7f7] bg-[#082f80] p-6 text-white shadow-[0_8px_24px_rgba(8,47,128,0.12)]"><div className="flex items-center gap-2 text-sm font-semibold"><CircleGauge className="h-5 w-5 text-[#8bb5ff]" />Plant health score</div><p className="mt-5 text-5xl font-semibold">94.7<span className="text-xl text-[#9bb8e7]">%</span></p><div className="mt-5 flex items-center gap-2 text-sm text-[#bcd2f4]"><ArrowUpRight className="h-4 w-4 text-[#68d6b0]" />2.4% from last review</div></div>
      </section>

      <section className="rounded-2xl border border-[#dce7f7] bg-white p-5 shadow-[0_8px_24px_rgba(8,47,128,0.06)]"><div className="flex items-center justify-between gap-4"><div><h3 className="text-base font-semibold text-[#082f80]">Machine condition</h3><p className="mt-1 text-sm text-[#6c83a4]">Select an asset to inspect its condition history and performance</p></div><Factory className="h-5 w-5 text-[#5c8ce8]" /></div><div className="mt-5 grid gap-3 md:grid-cols-5">{machines.map((item) => <button key={item.id} type="button" onClick={() => setSelectedMachine(item.id)} className={`rounded-xl border p-4 text-left transition-colors ${item.id === selectedMachine ? "border-[#1257c7] bg-[#eef4ff]" : "border-[#e7edf7] bg-[#fbfcff] hover:border-[#91b1ed]"}`}><div className="flex items-center justify-between"><span className={`h-2.5 w-2.5 rounded-full ${item.color}`} /><span className="text-[10px] font-bold uppercase tracking-wide text-[#7890b2]">{item.status}</span></div><p className="mt-4 text-sm font-semibold text-[#173e82]">{item.id}</p><p className="mt-1 min-h-8 text-xs leading-4 text-[#7890b2]">{item.name}</p><p className="mt-3 text-lg font-semibold text-[#082f80]">{item.health}</p></button>)}</div></section>

      <section className="grid gap-6 xl:grid-cols-[1.3fr_1fr]">
        <div className="space-y-6"><div className="rounded-2xl border border-[#dce7f7] bg-white shadow-[0_8px_24px_rgba(8,47,128,0.06)]"><div className="flex items-center justify-between border-b border-[#edf2fa] p-5"><div><h3 className="text-base font-semibold text-[#082f80]">Condition history · {machine.id}</h3><p className="mt-1 text-sm text-[#6c83a4]">Weekly vibration, coupling, and bearing readings</p></div><button type="button" className="flex items-center gap-2 rounded-lg border border-[#dce7f7] px-3 py-2 text-xs font-semibold text-[#45648d]">Last 3 readings <ChevronDown className="h-3.5 w-3.5" /></button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px]"><thead><tr className="bg-[#f8faff] text-left text-[10px] font-bold uppercase tracking-wider text-[#7890b2]"><th className="px-5 py-3">History date</th><th className="px-5 py-3">Overall vibration</th><th className="px-5 py-3">2X harmonic</th><th className="px-5 py-3">Coupling offset</th><th className="px-5 py-3">Bearing temp</th><th className="px-5 py-3">Health</th></tr></thead><tbody className="divide-y divide-[#edf2fa]">{conditionHistory.map((row) => <tr key={row[0]} className="text-sm text-[#45648d]"><td className="px-5 py-4 font-medium text-[#173e82]">{row[0]}</td>{row.slice(1, 5).map((value) => <td key={value} className="px-5 py-4 font-mono">{value}</td>)}<td className="px-5 py-4"><span className="inline-flex items-center gap-1.5 rounded-full bg-[#eaf8ef] px-2 py-1 text-xs font-semibold text-[#25824b]"><CheckCircle2 className="h-3.5 w-3.5" />{row[5]}</span></td></tr>)}</tbody></table></div></div><div className="rounded-2xl border border-[#dce7f7] bg-white shadow-[0_8px_24px_rgba(8,47,128,0.06)]"><div className="border-b border-[#edf2fa] p-5"><h3 className="text-base font-semibold text-[#082f80]">Performance summary · {machine.id}</h3><p className="mt-1 text-sm text-[#6c83a4]">Reliability and production impact from the monitoring window</p></div><div className="overflow-x-auto"><table className="w-full min-w-[640px]"><thead><tr className="bg-[#f8faff] text-left text-[10px] font-bold uppercase tracking-wider text-[#7890b2]"><th className="px-5 py-3">KPI</th><th className="px-5 py-3">Value</th><th className="px-5 py-3">Basis / </th></tr></thead><tbody className="divide-y divide-[#edf2fa]">{performanceSummary.map(([label, value, _basis]) => <tr key={label} className="text-sm"><td className="px-5 py-3.5 font-medium text-[#173e82]">{label}</td><td className="px-5 py-3.5 font-mono font-semibold text-[#082f80]">{value}</td><td className="px-5 py-3.5 text-[#7890b2]">{_basis}</td></tr>)}</tbody></table></div></div></div>
        <aside className="rounded-2xl border-2 border-[#1257c7] bg-white p-5 shadow-[0_12px_32px_rgba(18,87,199,0.12)]"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#1257c7] text-white"><ShieldAlert className="h-5 w-5" /></div><div><h3 className="font-semibold text-[#082f80]">Root-cause insights</h3><p className="text-xs text-[#7890b2]">Select an insight to inspect the evidence and response</p></div></div><div className="mt-5 space-y-2">{insights.map((insight, index) => <button key={insight.title} type="button" onClick={() => setSelectedInsight(index)} className={`w-full rounded-xl border p-4 text-left transition-colors ${index === selectedInsight ? "border-[#1257c7] bg-[#eef4ff]" : "border-[#e7edf7] bg-[#f8faff] hover:border-[#91b1ed]"}`}><div className="flex items-start justify-between gap-3"><h4 className="text-sm font-semibold leading-5 text-[#173e82]">{insight.title}</h4><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-bold ${insight.tone === "red" ? "bg-[#fff0f0] text-[#bf3d4b]" : insight.tone === "amber" ? "bg-[#fff8e8] text-[#b57616]" : "bg-[#eef4ff] text-[#1257c7]"}`}>{insight.tag}</span></div><p className="mt-2 text-xs leading-5 text-[#6c83a4]">{insight.text}</p></button>)}</div><div className="mt-4 rounded-xl border border-[#dce7f7] bg-[#f8faff] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#7890b2]">Related evidence</p><p className="mt-2 text-xs leading-5 text-[#45648d]">{activeInsight.evidence}</p><div className="mt-4 border-t border-[#e3ebf7] pt-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#7890b2]">Recommended action</p><p className="mt-2 text-xs leading-5 text-[#173e82]">{activeInsight.action}</p></div></div><div className="mt-4 rounded-xl bg-[#082f80] p-4 text-white"><div className="flex items-center gap-2 text-sm font-semibold"><AlertTriangle className="h-4 w-4 text-[#f4bf5e]" />Next review focus</div><p className="mt-2 text-xs leading-5 text-[#c5d7f3]">{activeInsight.action}</p></div></aside>
      </section>
    </div>
  );
}
